# This YAML file specifies all the paths settings required by the script for training and
# inference.So that this is the only file to modify before running the flow. 

---
 # Add all the data points to be used for training in this directory
 training_data_path: "./data/data_set_2/train/"
 # Add all the data points to be used for testing in this directory
 testing_data_path: "./data/data_set_2/test/"        
 # Path for output plots on test data:
 output_plot_path: "./output/"
 chip_size_x: 34
 chip_size_y: 32
 tile_size: 250e-6
 num_time_steps: 45
 percent_valid_split: 0.1 # 10 percent of training points is used for validation during training
 learning_rate: 0.0005
 decay_steps: 1000
 decay_rate: 0.98
 epochs: 500
